version: "3"

services:

  backend:
    build: .
    container_name: backend
    stdin_open: true
    tty: true
    volumes:
      - "./:/code/build"
    ports:
      - "8001:8001"
    env_file:
      - .env
    environment:
      - MODE=runserver
    depends_on:
      - postgres
      - rabbitmq
      - memcached

  celery:
    build: .
    container_name: celery
    stdin_open: true
    tty: true
    volumes:
      - "./:/code/build"
    env_file:
      - .env
    environment:
      - MODE=celery
    depends_on:
      - postgres
      - rabbitmq
      - memcached

  celerybeat:
    build: .
    container_name: celerybeat
    stdin_open: true
    tty: true
    volumes:
      - "./:/code/build"
    env_file:
      - .env
    environment:
      - MODE=celerybeat
    depends_on:
      - rabbitmq

  flower:
    build: .
    container_name: flower
    stdin_open: true
    tty: true
    volumes:
      - "./:/code/build"
    ports:
      - "5555:5555"
    env_file:
      - .env
    environment:
      - MODE=flower
    depends_on:
      - celery

  memcached:
    image: memcached
    container_name: memcached
    env_file:
      - .env
    ports:
      - "11211:11211"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    env_file:
      - .env
    ports:
      - "5050:5050"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    env_file:
      - .env
    ports:
      - "15672:15672"
      - "5672:5672"

  postgres:
    image: postgres:13.4-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "8080:80"
    # volumes:
    #   - "./default.conf:/etc/nginx/conf.d/default.conf:ro"
    depends_on:
      - backend

volumes:
  db_data: {}